apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc001
provisioner: ingram.io/nfs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
