apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 250Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfsshare/registry
    server: 10.122.0.151
