apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_USER: dXNlcjE=
  MYSQL_PASSWORD: bXlwYTU1
  MYSQL_DATABASE: dGVzdGRi
  MYSQL_ROOT_PASSWORD: cjAwdHBhNTU=
