apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2021-09-01T02:50:32Z"
  generation: 3
  labels:
    app: mysql-openshift
    app.kubernetes.io/component: mysql-openshift
    app.kubernetes.io/instance: mysql-openshift
  name: mysql-openshift
  namespace: mysql
  resourceVersion: "1004040"
  uid: 14363d7b-e350-46ac-b3c0-87b1d07ccf42
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: mysql-openshift
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: mysql-openshift
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_PASSWORD
          value: mypa55
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55
        - name: MYSQL_USER
          value: user1
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
        imagePullPolicy: Always
        name: mysql-openshift
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mysql-openshift
      from:
        kind: ImageStreamTag
        name: mysql-openshift:latest
        namespace: mysql
      lastTriggeredImage: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-01T05:05:51Z"
    lastUpdateTime: "2021-09-01T05:05:54Z"
    message: replication controller "mysql-openshift-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-09-01T05:17:31Z"
    lastUpdateTime: "2021-09-01T05:17:31Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
