use testdb;
create table testtab (id int(3) not null, name varchar(255) default null, primary key(id));
insert into testtab (id, name) values (1, 'Alan');
insert into testtab (id, name) values (2, 'Ben');
insert into testtab (id, name) values (3, 'Cathy');
insert into testtab (id, name) values (4, 'David');
insert into testtab (id, name) values (5, 'Eden');
insert into testtab (id, name) values (6, 'Francis');
insert into testtab (id, name) values (7, 'George');
insert into testtab (id, name) values (8, 'Harry');
insert into testtab (id, name) values (9, 'Ivan');
insert into testtab (id, name) values (10, 'Jeffrey');
