apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolciy: Retain
  vsphereVolume:
    volumePath: "/vmfs/volumes/Datastore/volumes/"
    fstype: ext4
