apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - worker01.ibm.example.com
        - worker02.ibm.example.com
        - worker03.ibm.example.com
  storageClassDevices:
    - storageClassName: localblock-sc
      volumeMode: Block
      devicePaths:
        - /dev/sdb
