apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs5200-pvc
  namespace: ibm-block-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: block
