apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs5200-pvc
  namespace: ibm-storage-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fs5200
